/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gurpreet;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import twitter4j.*;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;
import twitter4j.auth.AccessToken;


/**
 *
 * @author Gurpreet
 */
public class NewHone extends javax.swing.JFrame {

    /**
     * Creates new form NewHone
     */
    
    List<Status> statuses = new ArrayList();
    static String consumerKeyStr ;
    static String consumerSecretStr ;
    static String accessTokenStr ;
    static String accessTokenSecretStr;
    
   static String user;
    public NewHone(String username) {
        initComponents();
        
        try
        {
            user=username;
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
            PreparedStatement ps=con.prepareStatement("select * from final where email=?");
            ps.setString(1,username);
         
            ResultSet rs=ps.executeQuery();
            if(rs.next())
            {
                consumerKeyStr =rs.getString(3).trim();
                consumerSecretStr=rs.getString(4).trim();
                accessTokenStr =rs.getString(5).trim();
                accessTokenSecretStr=rs.getString(6).trim();
            }    
           
           Twitter twitter = new TwitterFactory().getInstance();
            twitter.setOAuthConsumer(consumerKeyStr, consumerSecretStr);
            AccessToken accessToken = new AccessToken(accessTokenStr,accessTokenSecretStr);
            twitter.setOAuthAccessToken(accessToken);
            
            id.setText(id.getText()+""+twitter.getScreenName());
            
            
           User user = twitter.showUser(twitter.getId());
           URL url =user.getProfileImageUrlHttps();
           ImageIcon img1 =new ImageIcon(url);
           img.setIcon(img1);

           
           statuses.addAll(twitter.getUserTimeline());
           for (Status status : statuses) 
           {
              twt.setText(twt.getText()+"\n"+"Post Date-:"+status.getCreatedAt()+"\n@" + status.getUser().getScreenName() + " - " + status.getText());
           }
           
           DefaultListModel dl=new DefaultListModel();
           int count = 0;
           int i=1;
           Trends trends = twitter.getPlaceTrends(1);
           for (Trend trend : trends.getTrends()) 
            {
                if (count < 10)
                {
                     dl.addElement(i+". "+trend.getName());  
                     i++;
                     count++;
                 }
            }
            list1.setModel(dl);

             // Fallower List
             DefaultListModel d2=new DefaultListModel();
              String twitterScreenName = twitter.getScreenName();
              PagableResponseList<User> statuse = twitter.getFollowersList(twitterScreenName, -1);
               for (User follower : statuse) 
              {
                 d2.addElement(follower.getName()+"/"+follower.getId());
              }
               list2.setModel(d2);


        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }

    NewHone() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        twt = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        file = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FleetTweet V1.0");
        setBounds(new java.awt.Rectangle(450, 150, 0, 0));
        setMinimumSize(new java.awt.Dimension(1050, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        twt.setColumns(20);
        twt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        twt.setRows(5);
        jScrollPane2.setViewportView(twt);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(300, 270, 470, 420);

        list2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(list2);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 270, 280, 420);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gurpreet\\Desktop\\project\\New folder\\1920x1080-white-solid-color-background.jpg")); // NOI18N
        jPanel2.add(img);
        img.setBounds(960, 10, 70, 50);

        id.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        id.setText("Log In-:");
        jPanel2.add(id);
        id.setBounds(810, 70, 220, 20);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 102));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gurpreet\\Desktop\\project\\symbols\\bb.png")); // NOI18N
        jButton6.setText("History");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(530, 20, 130, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gurpreet\\Desktop\\project\\symbols\\home.jpg")); // NOI18N
        jButton3.setText(" Home");
        jButton3.setBorder(null);
        jPanel2.add(jButton3);
        jButton3.setBounds(370, 20, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("My Tweets:-");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(300, 230, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("List Of Followers :-");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 230, 230, 30);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 102, 102));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gurpreet\\Desktop\\project\\symbols\\settings.jpg")); // NOI18N
        jButton7.setText("Settings");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(710, 20, 130, 40);

        tf1.setColumns(20);
        tf1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf1.setRows(5);
        jScrollPane1.setViewportView(tf1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(510, 100, 500, 90);

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("UPLOAD IMAGES/VIDEOS");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 170, 250, 40);
        jPanel2.add(file);
        file.setBounds(10, 110, 360, 40);

        jButton5.setBackground(new java.awt.Color(0, 51, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LogOut");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(780, 650, 150, 40);

        jButton9.setBackground(new java.awt.Color(0, 51, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Tweet");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(780, 210, 230, 40);

        list1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane3.setViewportView(list1);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(780, 320, 230, 320);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton10.setForeground(new java.awt.Color(102, 102, 102));
        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gurpreet\\Desktop\\project\\symbols\\profile.jpg")); // NOI18N
        jButton10.setText("Browse");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(380, 110, 120, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gurpreet\\Desktop\\project\\symbols\\trendings.jpg")); // NOI18N
        jLabel7.setText("Trendings");
        jPanel1.add(jLabel7);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(780, 270, 230, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gurpreet\\Desktop\\home.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1040, 700);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1040, 700);

        jButton8.setBackground(new java.awt.Color(0, 51, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Tweet");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(840, 180, 170, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
        {
           
                String msg=JOptionPane.showInputDialog("Enter Your Message");
            
                Twitter twitter = new TwitterFactory().getInstance();
                twitter.setOAuthConsumer(consumerKeyStr, consumerSecretStr);
                AccessToken accessToken = new AccessToken(accessTokenStr,accessTokenSecretStr);
                twitter.setOAuthAccessToken(accessToken);
                
                StatusUpdate update=new StatusUpdate(msg);
                update.setMedia(new File(file.getText()));
               
                twitter.updateStatus(update);
           
                JOptionPane.showMessageDialog(this,"Successfully updated the File.");
                
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new NewHistory().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new NewSettings().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list2MouseClicked
        // TODO add your handling code here:
        int count=evt.getClickCount();
        
        if(count==2)
        {
            try
            {
                String message=JOptionPane.showInputDialog("Enter Your Message To Send");
                String data=list2.getSelectedValue();
                
                String data1[]=data.split("/");
                Twitter twitter = new TwitterFactory().getInstance();
                twitter.setOAuthConsumer(consumerKeyStr, consumerSecretStr);
                AccessToken accessToken = new AccessToken(accessTokenStr,accessTokenSecretStr);
                twitter.setOAuthAccessToken(accessToken);
                DirectMessage directMessage = twitter.sendDirectMessage(Long.parseLong(data1[1]),message);
               JOptionPane.showMessageDialog(this,"Direct message successfully sent to \n" + directMessage.getRecipientScreenName());
            }
            catch(Exception e)
            {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_list2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
        new NewLogin().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         try
        {
           
                Twitter twitter = new TwitterFactory().getInstance();
                twitter.setOAuthConsumer(consumerKeyStr, consumerSecretStr);
                AccessToken accessToken = new AccessToken(accessTokenStr,accessTokenSecretStr);
                twitter.setOAuthAccessToken(accessToken);
                twitter.updateStatus(tf1.getText());
           
                JOptionPane.showMessageDialog(this,"Successfully updated the status in Twitter.");
                tf1.setText("");
                
                
                 twt.setText("");
                twitter.setOAuthAccessToken(accessToken);
               statuses.addAll(twitter.getUserTimeline());
               for (Status status : statuses) 
               {
                  twt.setText(twt.getText()+"\n"+"Post Date-:"+status.getCreatedAt()+"\n@" + status.getUser().getScreenName() + " - " + status.getText());
               }

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc=new JFileChooser();
        int i=fc.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION)
        {
            File f=fc.getSelectedFile();
            file.setText(f.getPath());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewHone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewHone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewHone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewHone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewHone(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField file;
    private javax.swing.JLabel id;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> list1;
    private javax.swing.JList<String> list2;
    private javax.swing.JTextArea tf1;
    private javax.swing.JTextArea twt;
    // End of variables declaration//GEN-END:variables
}
